LocalParks/Controllers/ParksController.cs
using LocalParks.Core.Contracts;
using LocalParks.Core.Models;
using LocalParks.Services.View;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace LocalParks.Controllers
{
    [BindProperties]
    public class ParksController : Controller
    {
        private readonly IParksService _service;

        public ParksController(IParksService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var results = await _service.GetAllModelsAsync();

            return View(results);
        }

        public async Task<IActionResult> Filter(
            [FromServices] ISortingService sortingService,
            string searchTerm = null,
            string postcode = null,
            string sortBy = null,
            string openOnly = null)
        {
            var openFilter = !string.IsNullOrEmpty(openOnly);
            var matches = await _service.GetSearchedAsync(searchTerm, postcode, openFilter);

            if (matches != null)
            {
                TempData["Filter"] = searchTerm;

                if (!string.IsNullOrWhiteSpace(sortBy) ||
                    !string.IsNullOrWhiteSpace(postcode) ||
                    openFilter) TempData["Sorted"] = "true";
            }
            else
            {
                TempData["Matches"] = "No Matches found";

                matches = await _service.GetAllModelsAsync();
            }

            if (!string.IsNullOrWhiteSpace(sortBy))
                matches = sortingService.SortResults<ParkModel>(matches, sortBy);

            return View("Index", matches);
        }

        public async Task<IActionResult> Details(int parkId)
        {
            var park = await _service.GetParkAsync(parkId);

            return View(park);
        }

    }
}

LocalParks/Controllers/SportsClubsController.cs
using LocalParks.Core.Contracts;
using LocalParks.Core.Models;
using LocalParks.Services.View;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace LocalParks.Controllers
{
    [BindProperties]
    public class SportsClubsController : Controller
    {
        private readonly ISportsClubsService _service;

        public SportsClubsController(ISportsClubsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["Sports"] = _service.GetSportListItems();

            var results = await _service.GetSearchedSportsClubModelsAsync();

            return View(results);
        }
        public async Task<IActionResult> Filter(
            [FromServices] ISortingService sortingService,
            string searchTerm = null,
            string parkFilter = null,
            string sportType = null,
            string sortBy = null)
        {
            ViewData["Sports"] = _service.GetSportListItems();

            var matches = await _service.GetSearchedSportsClubModelsAsync(
                searchTerm, parkFilter, sportType);

            if (matches != null)
            {
                TempData["Filter"] = searchTerm;

                if (!string.IsNullOrWhiteSpace(sortBy) ||
                    !string.IsNullOrWhiteSpace(parkFilter) ||
                    !string.IsNullOrWhiteSpace(sportType)) TempData["Sorted"] = "true";
            }
            else
            {
                TempData["Matches"] = "No Matches found";

                matches = await _service.GetAllSportsClubModelsAsync();

            }

            if (!string.IsNullOrWhiteSpace(sortBy))
                matches = sortingService.SortResults(matches, sortBy);

            return View("Index", matches);

        }
        public async Task<IActionResult> Details(int sportsClubId)
        {
            var sportsClub = await _service.GetSportsClubModelAsync(sportsClubId);

            if (sportsClub == null) return View("NotFound");

            return View(sportsClub);
        }
    }
}

LocalParks/Controllers/SupervisorsController.cs
using LocalParks.Core.Contracts;
using LocalParks.Core.Models;
using LocalParks.Services.View;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace LocalParks.Controllers
{
    public class SupervisorsController : Controller
    {
        private readonly ISupervisorsService _service;

        public SupervisorsController(ISupervisorsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var results = await _service.GetAllSupervisorModelsAsync();
            return View(results);
        }

        public async Task<IActionResult> Filter(
            [FromServices] ISortingService sortingService,
            string searchTerm = null,
            string parkFilter = null,
            string sortBy = null)
        {
            var matches = await _service.GetSearchedSupervisorModelsAsync(
                searchTerm, parkFilter);

            if (matches != null)
            {
                TempData["Filter"] = searchTerm;

                if (!string.IsNullOrWhiteSpace(sortBy) ||
                    !string.IsNullOrWhiteSpace(parkFilter)) TempData["Sorted"] = "true";
            }
            else
            {
                TempData["Matches"] = "No Matches found";

                matches = await _service.GetAllSupervisorModelsAsync();
            }

            if (!string.IsNullOrWhiteSpace(sortBy))
                matches = sortingService.SortResults<SupervisorModel>(matches, sortBy);

            return View("Index", matches);
        }

        public async Task<IActionResult> Details(int parkId)
        {
            var supervisor = await _service.GetSupervisorModelAsync(parkId);

            if (supervisor == null) return View("NotFound");

            return View(supervisor);
        }
    }
}

LocalParks/Views/Parks/Details.cshtml
@model ParkModel
@inject IEncryptionService service
@{
    ViewData["Title"] = $"{Model.Name} Details";
}

<div class="m-2">
    <input class="btn-dark w3-hover-border-amber w3-hover-text-amber rounded"
           type="button" value="All parks"
           onclick="location.href='@Url.Action("Index", "Parks")'" />
</div>

<div class="jumbotron row m-2">
    <ul class="w-100 list-unstyled d-flex flex-row justify-content-between flex-wrap">
        <li class="flex-column position-relative">
            <h2>@Model.Name</h2>
        </li>
        <li class="flex-column position-relative">
            @if (Model.IsOpen())
            {
                <h4 class="font-weight-bold border-success bg-success p-2 rounded text-dark">
                    Currently Open
                </h4>
            }
            else
            {
                <h4 class="font-weight-bold border-danger bg-danger p-2 rounded text-light">
                    Currently Closed
                </h4>
            }
        </li>
    </ul>
</div>
<div class="d-flex flex-row justify-content-around flex-wrap alert-warning ">
    <h4 class="font-weight-bold">
        <i class="fa fa-clock"></i>
        Opening and closing times:
    </h4>
    <h5>
        @Model.OpeningTime.ToString("hh:mm tt") - @Model.ClosingTime.ToString("hh:mm tt")
    </h5>
</div>
<div class="d-flex flex-row justify-content-around flex-wrap font-weight-bold">
    <h5>
        <span>Located in: </span>
        <input class="btn-dark w3-hover-border-amber w3-hover-text-amber rounded" type="button"
               value="@Model.PostcodeNeighbourhood"
               onclick="location.href='@Url.Action("Filter", "Parks", new { postcode = Model.PostcodeZone })'" />
        <span> (@Model.PostcodeZone)</span>
    </h5>
    <h5>
        @if (Model.Supervisor != null)
        {
            <span>Park Supervisor: </span>
            <input class="btn-dark w3-hover-border-amber w3-hover-text-amber rounded" type="button"
                   value="@Model.Supervisor.FirstName @Model.Supervisor.LastName"
                   onclick="location.href='@Url.Action("Details", "Supervisors", new { _lp = @service.Encrypt("parkId",Model.ParkId) })'" />
        }
        else
        {
            <span>Currently Hiring for supervisor postion!</span>
            <input class="btn-dark w3-hover-border-amber w3-hover-text-amber rounded" type="button"
                   value=" See all other staff"
                   onclick="location.href='@Url.Action("Index", "Supervisors")'" />

        }
    </h5>
</div>

<div class="p-1 m-1 card border-info">
    <h5 class="font-weight-bolder text-info text-center"><ins>Information</ins></h5>
    <div>
        <ul class="list-unstyled d-flex flex-row justify-content-around flex-wrap ">
            <li class="flex-column position-relative">
                <span class="font-weight-bold">Latitude:</span>
                @Model.Latitude &deg
            </li>
            <li class="flex-column position-relative">
                <span class="font-weight-bold">Longitude:</span>
                @Model.Longitude &deg
            </li>
            <li class="flex-column position-relative">
                <span class="font-weight-bold">Park Overall Area:</span>
                @Model.SizeInMetresSquared m&sup2
            </li>
        </ul>
    </div>
</div>

<div class="d-flex flex-row justify-content-around flex-wrap m-1">
    @if (Model.SportClubs.Any())
    {
        <div class="flex-column">
            <a class="w3-blue rounded font-weight-bolder card p-1 d-flex flex-row justify-content-between flex-wrap m-1 bg-light" href="#SportsClubsCollapse" role="button" data-toggle="collapse"
               aria-expanded="false" aria-controls="SportsClubsCollapse">
                <span class="text-decoration-none p-1">
                    <i class="fa fa-football-ball"></i> Sports Clubs <span class="w3-text-deep-orange bg-dark pr-2 pl-2 rounded">@Model.SportClubs.Count</span>
                </span>

            </a>
            <div class="collapse bg-light" id="SportsClubsCollapse">
                @foreach (var club in Model.SportClubs)
                {
                    <div class="flex-column position-relative border-bottom">
                        <ul class="list-unstyled d-flex flex-row justify-content-around flex-wrap align-items-center">
                            <li class="flex-column position-relative font-weight-bolder">
                                @club.Name
                            </li>
                            <li class="flex-column position-relative alert rounded">
                                @club.Sport.ToString()
                            </li>
                            <li class="flex-column position-relative">
                                <input class="btn-dark w3-hover-border-amber w3-hover-text-amber rounded"
                                       type="button"
                                       value="See Details"
                                       onclick="location.href='@Url.Action("Details", "SportsClubs",
                                new { _lp = @service.Encrypt("sportsClubId",club.ClubId) })'" />
                            </li>
                        </ul>
                    </div>
                }
                <input class="w3-hover-border-amber w3-hover-text-amber rounded" type="button"
                       value="See all"
                       onclick="location.href='@Url.Action("Filter", "SportsClubs", new { _lp = service.Encrypt("parkFilter",Model.ParkId) })'" />
            </div>
        </div>
    }
    else
    {
        <p>This park doesn't have any sport clubs.</p>
    }
    @if (Model.Events.Any())
    {
        <div class="flex-column">
            <a class="w3-green rounded font-weight-bolder card p-1 d-flex flex-row justify-content-between flex-wrap m-1 bg-light" href="#EventsCollapse" role="button" data-toggle="collapse"
               aria-expanded="false" aria-controls="EventsCollapse">
                <span class="text-decoration-none p-1">
                    <i class="fa fa-calendar-check"></i> Scheduled Events <span class="w3-text-deep-orange bg-dark pr-2 pl-2 rounded">@Model.Events.Count</span>
                </span>

            </a>
            <div class="collapse bg-light" id="EventsCollapse">
                @foreach (var parkEvent in Model.Events)
                {
                    <div class="flex-column position-relative border-bottom">
                        <ul class="list-unstyled list-unstyled d-flex flex-row justify-content-around flex-wrap align-items-center">
                            <li class="flex-column position-relative font-weight-bolder ">
                                @parkEvent.Name
                            </li>
                            <li class="flex-column position-relative alert rounded">
                                @parkEvent.Date.ToLongDateString()
                            </li>
                            <li class="flex-column position-relative">
                                <input class="btn-dark w3-hover-border-amber w3-hover-text-amber rounded btn-sm"
                                       type="button"
                                       value="See Details"
                                       onclick="location.href='@Url.Action("Details", "ParkEvents",
                                                                          new { _lp = @service.Encrypt("eventId",parkEvent.EventId)})'" />
                            </li>
                        </ul>
                    </div>
                }
                <input class="w3-hover-border-amber w3-hover-text-amber rounded" type="button"
                       value="See all"
                       onclick="location.href='@Url.Action("Filter", "ParkEvents", new { _lp = service.Encrypt("parkFilter",Model.ParkId) })'" />
            </div>
        </div>
    }
    else
    {
        <p class="font-weight-bolder">This park doesn't have any events scheduled.</p>
    }
</div>

LocalParks/Views/Parks/Index.cshtml
@model ICollection<ParkModel>
@{
    ViewData["Title"] = "Parks";
}

@section scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/filtering.js"></script>
}

<div class="parks-jumbotron-img">
    <div class="p-1 pr-3 pl-3 bg-light rounded w-auto d-inline-block">
        <h1>Your Local Parks</h1>
    </div>
</div>

<partial name="_FilterBar" />

<div class="bg-info border-dark text-dark w-auto rounded text-center m-1">Viewing <strong>@Model.Count()</strong> of our parks.</div>

@foreach (var park in Model)
{
    <partial name="_Summary" model="park" />
}

LocalParks/Views/Parks/NotFound.cshtml
<title>Error 404 - Page not found</title>

<h2>Not Found.</h2>

<input class="btn-dark w3-hover-border-amber w3-hover-text-amber rounded btn-sm" 
       type="button" 
       value="Go back to Parks" 
       onclick="location.href='@Url.Action("Index", "Parks")'" />

LocalParks/Views/Parks/_FilterBar.cshtml
@model ICollection<ParkModel>
@inject ISelectListService service
<div class="index-filter-form w3-pale-green m-1 p-2 rounded">
    <form id="filter-form-supervisors" asp-controller="Parks" asp-action="Filter" method="get">
        <div class="d-flex flex-wrap flex-row justify-content-between font-weight-bolder w-100">

            <div class="w3-margin-right w3-margin-left w-auto d-inline-block">
                <div class="row">
                    <label>Park name:</label>
                    <input type="text" class="border-dark rounded filter-form-group" name="searchTerm" value="@TempData["Filter"]" />
                </div>
            </div>
            <div class="w3-margin-right w3-margin-left w-auto d-inline-block">
                <div class="row">
                    <label>Postcode:</label>
                    @Html.DropDownList("Postcode",
       new SelectList((System.Collections.IEnumerable)await service.GetPostcodeSelectListItemsAsync(), "Value", "Text"), "",
       htmlAttributes: new
       {
           @class = "border-dark rounded filter-form-group",
           name = "postcode",
           style = "min-width: 8%;"
       })
                </div>
            </div>

            <div class="w3-margin-right w3-margin-left w-auto d-inline-block">
                <div class="row">
                    <label>Sort by:</label>
                    @Html.DropDownList("SortBy",
                   new SelectList((System.Collections.IEnumerable)service.GetSortSelectListItems<ParkModel>(), "Value", "Text"), "",
                   htmlAttributes: new
                   {
                       @class = "border-dark rounded filter-form-group",
                       name = "sortBy",
                       style = "min-width: 8%;"
                   })
                </div>
            </div>

            <div class="w3-margin-right w3-margin-left w-auto d-inline-block">
                <label>Open Only:</label>
                <input name="openOnly"
                       type="checkbox"
                       class="border-dark rounded filter-form-group" />
            </div>

            <div class="w-auto">
                <input type="submit" class="btn-outline-light btn-dark btn-light rounded" value="Filter and Sort" />
            </div>
        </div>
    </form>
</div>

@if (TempData["Matches"] != null)
{
    <span class="alert-danger rounded w3-margin-left">@TempData["Matches"]</span>
}

@if (@TempData["Sorted"] != null || @TempData["Filter"] != null)
{
    <form asp-controller="Parks" asp-action="Index" method="get" class="d-inline-flex">
        <p>
            <input type="submit" value="Remove Filters and Sort" class="border-danger text-danger m-1" />
        </p>
    </form>
}

LocalParks/Views/Parks/_Summary.cshtml
@using LocalParks.Models
@inject IEncryptionService service
@model ParkModel
<div class="row summary-row-container">
    <div class="col-10 offset-1">
        <a asp-controller="Parks" asp-action="Details" asp-route-_lp="@service.Encrypt("parkId",Model.ParkId)"
           class="w3-hover-text-amber w3-hover-border-amber">
            <div class="d-flex flex-row justify-content-between flex-wrap p-1 card border align-items-center">

                <div class="flex-column position-relative">
                    <h2 class="bg-light font-weight-bolder text-info shadow">@Model.Name</h2>
                    @if (Model.IsOpen())
                    {
                        <h4 class="alert-warning font-weight-bold">
                            <i class="fa fa-clock"></i>
                            Closes: @Model.ClosingTime.ToString("hh:mm tt")
                        </h4>

                    }
                    else
                    {
                        <h4 class="alert-warning font-weight-bold">
                            <i class="fa fa-clock"></i>
                            Opens: @Model.OpeningTime.ToString("hh:mm tt")
                        </h4>
                    }
                </div>
                <div class="flex-column position-relative">
                    @if (Model.IsOpen())
                    {
                        <h4 class="font-weight-bold border-success bg-success p-2 rounded text-dark">
                            Open
                        </h4>
                    }
                    else
                    {
                        <h4 class="font-weight-bold border-danger bg-danger p-2 rounded text-light">
                            Closed
                        </h4>
                    }
                </div>

                <div class="flex-column position-relative w3-text-orange">
                    <table class="table summary-table-condensed table-striped dt-responsive w3-center rounded m-0 p-0">
                        <thead class="thead-light">
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.PostcodeZone)</th>
                                <th>@Html.DisplayNameFor(model => model.SportClubs)</th>
                                <th>@Html.DisplayNameFor(model => model.Events)</th>
                            </tr>
                        </thead>
                        <tbody Class="w3-text-deep-orange">
                            <tr >
                                <td>@Model.PostcodeZone</td>
                                <td>@Model.SportClubs.Count()</td>
                                <td>@Model.Events.Count()</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </a>
    </div>
</div>