LocalParks/Models/Reports/ChartViewModel.cs
using LocalParks.Core.Chart;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace LocalParks.Models.Chart
{
    public class ChartViewModel
    {
        private readonly string _json;
        private readonly ReportChart _chartData;

        public ChartViewModel(ReportChart chartData)
        {
            _chartData = chartData;
            _json = JsonConvert.SerializeObject(chartData, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            });

            _json = _json.Replace("scatterData", "data");
        }
        public ReportChart ChartData { get => _chartData; }
        public string Json { get => _json; }
    }
}

LocalParks/Controllers/ParkEventsController.cs
using LocalParks.Core.Contracts;
using LocalParks.Core.Contracts.Managers;
using LocalParks.Core.Models;
using LocalParks.Services.View;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace LocalParks.Controllers
{
    public class ParkEventsController : Controller
    {
        private readonly IParkEventsService _service;
        private readonly IAuthenticationService _authenticationService;
        private ParkEventModel _tempEvent;

        public ParkEventsController(IParkEventsService service,
            IAuthenticationService authenticationService)
        {
            _service = service;
            _authenticationService = authenticationService;
        }

        [BindProperty]
        public ParkEventModel Event
        {
            get { return _tempEvent; }
            set { _tempEvent = value; }
        }

        public async Task<IActionResult> Index()
        {
            var results = await _service.GetAllParkEventModelsAsync();

            return View(results);
        }

        public async Task<IActionResult> Filter(
            [FromServices] ISortingService sortingService,
            string searchTerm = null,
            string parkFilter = null,
            DateTime? date = null,
            string sortBy = null)
        {
            var matches = await _service.GetSearchedParkEventModelsAsync(
                searchTerm, parkFilter, date);

            if (matches != null)
            {
                if (!string.IsNullOrWhiteSpace(searchTerm)) TempData["Filter"] = searchTerm;

                else if (!string.IsNullOrWhiteSpace(sortBy) ||
                    !string.IsNullOrWhiteSpace(parkFilter) ||
                    date.HasValue) TempData["Sorted"] = "true";
            }
            else
            {
                TempData["Matches"] = "No Matches found";

                matches = await _service.GetAllParkEventModelsAsync();
            }

            if (!string.IsNullOrWhiteSpace(sortBy))
                matches = sortingService.SortResults(matches, sortBy);

            return View("Index", matches);
        }

        public async Task<IActionResult> Details([FromServices] IParkEventsManager parkEventsManager, int eventId
            )
        {
            var parkEvent = await _service.GetParkEventModelByIdAsync(eventId);

            ViewData["User"] = await parkEventsManager.IsUserAuthorizedAsync(User?.Identity.Name, parkEvent);

            return View(parkEvent);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int eventId)
        {
            if (!await _authenticationService.IsSignedInAsync(User))
                return RedirectToAction("Index", "ParkEvents");

            if (eventId != 0 && await HasEditAccessAsync(eventId))
                return RedirectToAction("Details", "ParkEvents", new { eventId });
            else if (eventId == 0)
                return View(_service.GetNewEvent());

            var result = await _service.GetParkEventModelByIdAsync(eventId);

            if (result == null) return View("NotFound");

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit()
        {
            if (!await _authenticationService.IsSignedInAsync(User))
                return RedirectToAction("Details", "ParkEvents",
                    new { _tempEvent.ParkId, _tempEvent.Date });

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Invalid fields - see fields for issues.");
                return View("Edit", _tempEvent);
            }

            var match = await _service.GetParkAsync(_tempEvent.ParkId);
            if (match == null)
            {
                ModelState.AddModelError("", "This park doesn't exist");
                return View("Edit", _tempEvent);
            }

            if (match.Events.FirstOrDefault(e => e.Date == _tempEvent.Date && e.EventId != _tempEvent.EventId) != null)
            {
                ModelState.AddModelError("", $"{match.Name} already has an event scheduled on {_tempEvent.Date.ToShortDateString()} - please choose another date.");
                return View("Edit", _tempEvent);
            }

            var result = await _service.AddNewParkEventAsync(_tempEvent, User.Identity.Name, false);

            if (result != null)
            {
                return RedirectToAction("Details", "ParkEvents", new { result.EventId });
            }

            ModelState.AddModelError("", "Could not create event - please try again later, or contact us with an issue.");
            return View("Edit", _tempEvent);
        }

        [HttpPost]
        public async Task<IActionResult> EditExisting()
        {
            if (!await _authenticationService.IsSignedInAsync(User))
                return RedirectToAction("Details", "ParkEvents",
                    new { _tempEvent.ParkId, _tempEvent.Date });

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Invalid fields - see fields for issues.");
                return View("Edit", _tempEvent);
            }

            var existing = await _service.GetParkEventModelByIdAsync(_tempEvent.EventId);

            if (existing == null) return View("NotFound");

            var park = await _service.GetParkAsync(_tempEvent.ParkId);

            if (park == null)
            {
                ModelState.AddModelError("", "This park doesn't exist");
                return View("Edit", _tempEvent);
            }

            if (park.Events.FirstOrDefault(e => e.Date == _tempEvent.Date && e.EventId != _tempEvent.EventId) != null)
            {
                ModelState.AddModelError("", $"{park.Name} already has an event scheduled on {_tempEvent.Date.ToShortDateString()} - please choose another date.");
                return View("Edit", _tempEvent);
            }

            existing = _tempEvent;

            var result = await _service.UpdateParkEventAsync(existing);

            if (result != null)
            {
                return RedirectToAction("Details", "ParkEvents", new { result.EventId });
            }

            ModelState.AddModelError("", "Could not update event - please try again later, or contact us with an issue.");
            return View("Edit", _tempEvent);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int eventId)
        {
            if (!await _authenticationService.IsSignedInAsync(User))
                return RedirectToAction("Details", "ParkEvents", new { eventId });

            if (!await HasEditAccessAsync(eventId))
                return RedirectToAction("Details", "ParkEvents", new { eventId });

            var result = await _service.GetParkEventModelByIdAsync(eventId);
            if (result == null) RedirectToAction("NotFound", "ParkEvents");

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int eventId, bool confirmed)
        {
            if (!await _authenticationService.IsSignedInAsync(User))
                return RedirectToAction("Details", "ParkEvents", new { eventId });

            if (await HasEditAccessAsync(eventId))
                return RedirectToAction("Details", "ParkEvents", new { eventId });

            var result = await _service.GetParkEventModelByIdAsync(eventId);
            if (result == null) RedirectToAction("NotFound", "ParkEvents");

            if (!confirmed) return View(result);

            try
            {
                if (await _service.DeleteParkEventAsync(result))
                    return RedirectToAction("Index", "ParkEvents");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Could not delete event. Please contact us about this issue");
                return View(result);
            }

            return RedirectToAction("Details", "ParkEvents", new { eventId });
        }

        private async Task<bool> HasEditAccessAsync(int eventId)
        {
            return User.Identity != null &&
            await _service.GetEventOwner(eventId, User.Identity.Name) == null &&
            !await _authenticationService.HasRequiredRoleAsync(User.Identity.Name, "Administrator");
        }
    }
}

LocalParks/Controllers/ParksController.cs
using LocalParks.Core.Contracts;
using LocalParks.Core.Models;
using LocalParks.Services.View;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace LocalParks.Controllers
{
    [BindProperties]
    public class ParksController : Controller
    {
        private readonly IParksService _service;

        public ParksController(IParksService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var results = await _service.GetAllModelsAsync();

            return View(results);
        }

        public async Task<IActionResult> Filter(
            [FromServices] ISortingService sortingService,
            string searchTerm = null,
            string postcode = null,
            string sortBy = null,
            string openOnly = null)
        {
            var openFilter = !string.IsNullOrEmpty(openOnly);
            var matches = await _service.GetSearchedAsync(searchTerm, postcode, openFilter);

            if (matches != null)
            {
                TempData["Filter"] = searchTerm;

                if (!string.IsNullOrWhiteSpace(sortBy) ||
                    !string.IsNullOrWhiteSpace(postcode) ||
                    openFilter) TempData["Sorted"] = "true";
            }
            else
            {
                TempData["Matches"] = "No Matches found";

                matches = await _service.GetAllModelsAsync();
            }

            if (!string.IsNullOrWhiteSpace(sortBy))
                matches = sortingService.SortResults<ParkModel>(matches, sortBy);

            return View("Index", matches);
        }

        public async Task<IActionResult> Details(int parkId)
        {
            var park = await _service.GetParkAsync(parkId);

            return View(park);
        }

    }
}

LocalParks/Controllers/ReportsController.cs
using LocalParks.Services.Reports;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace LocalParks.Controllers
{
    public class ReportsController : Controller
    {
        public ReportsController()
        {
        }

        public async Task<IActionResult> Index([FromServices] IReportsService service)
        {
            var model = await service.GetReportsModelAsync();

            return View(model);
        }
        public IActionResult Parks()
        {
            return View();
        }
        public IActionResult Supervisors()
        {
            return View();
        }
        public IActionResult SportsClubs()
        {
            return View();
        }
        public IActionResult ParkEvents()
        {
            return View();
        }
        public IActionResult Shop()
        {
            return View();
        }
    }
}

LocalParks/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;

namespace LocalParks.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

LocalParks/Controllers/SportsClubsController.cs
using LocalParks.Core.Contracts;
using LocalParks.Core.Models;
using LocalParks.Services.View;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace LocalParks.Controllers
{
    [BindProperties]
    public class SportsClubsController : Controller
    {
        private readonly ISportsClubsService _service;

        public SportsClubsController(ISportsClubsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["Sports"] = _service.GetSportListItems();

            var results = await _service.GetSearchedSportsClubModelsAsync();

            return View(results);
        }
        public async Task<IActionResult> Filter(
            [FromServices] ISortingService sortingService,
            string searchTerm = null,
            string parkFilter = null,
            string sportType = null,
            string sortBy = null)
        {
            ViewData["Sports"] = _service.GetSportListItems();

            var matches = await _service.GetSearchedSportsClubModelsAsync(
                searchTerm, parkFilter, sportType);

            if (matches != null)
            {
                TempData["Filter"] = searchTerm;

                if (!string.IsNullOrWhiteSpace(sortBy) ||
                    !string.IsNullOrWhiteSpace(parkFilter) ||
                    !string.IsNullOrWhiteSpace(sportType)) TempData["Sorted"] = "true";
            }
            else
            {
                TempData["Matches"] = "No Matches found";

                matches = await _service.GetAllSportsClubModelsAsync();

            }

            if (!string.IsNullOrWhiteSpace(sortBy))
                matches = sortingService.SortResults(matches, sortBy);

            return View("Index", matches);

        }
        public async Task<IActionResult> Details(int sportsClubId)
        {
            var sportsClub = await _service.GetSportsClubModelAsync(sportsClubId);

            if (sportsClub == null) return View("NotFound");

            return View(sportsClub);
        }
    }
}

LocalParks/ViewComponents/EventsPerMonthChartViewComponent.cs
using LocalParks.Services.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LocalParks.ViewComponents
{
    public class EventsPerMonthChartViewComponent : ViewComponent
    {
        private readonly IChartService _service;

        public EventsPerMonthChartViewComponent(ChartServiceResolver resolver)
        {
            _service = resolver(ChartServiceType.EventsPerMonth);
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _service.CreateAsync();

            return View(model);
        }
    }
}

LocalParks/ViewComponents/ParksPerPostcodeViewComponent.cs
using LocalParks.Services.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LocalParks.ViewComponents
{
    public class ParksPerPostcodeChartViewComponent : ViewComponent
    {
        private readonly IChartService _service;

        public ParksPerPostcodeChartViewComponent(ChartServiceResolver resolver)
        {
            _service = resolver(ChartServiceType.ParksPerPostcode);
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _service.CreateAsync();

            return View(model);
        }
    }
}

LocalParks/ViewComponents/SalaryTenureChartViewComponent.cs
using LocalParks.Services.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LocalParks.ViewComponents
{
    public class SalaryTenureChartViewComponent : ViewComponent
    {
        private readonly IChartService _service;

        public SalaryTenureChartViewComponent(ChartServiceResolver resolver)
        {
            _service = resolver(ChartServiceType.SalaryTenure);
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _service.CreateAsync();

            return View(model);
        }
    }
}

LocalParks/ViewComponents/SportPercentageChartViewComponent.cs
using LocalParks.Services.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LocalParks.ViewComponents
{
    public class SportPercentageChartViewComponent : ViewComponent
    {
        private readonly IChartService _service;

        public SportPercentageChartViewComponent(ChartServiceResolver resolver)
        {
            _service = resolver(ChartServiceType.SportsPercentage);
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _service.CreateAsync();

            return View(model);
        }
    }
}

LocalParks/Views/Reports/Index.cshtml
@using LocalParks.Models.Reports
@model ReportsViewModel
@{
    ViewData["Title"] = "Reports";
}
<div class="bg-white p-4">
    
    <div class="reports-jumbotron-img">
        <div class="p-1 pr-3 pl-3 bg-light rounded w-auto d-inline-block">
            <h1>Local Parks Authority Statistics and Reports</h1>
        </div>
    </div>

    <div class="card row border p-2 bg-light col-10 offset-1">
        <p class="font-weight-bolder m-1">As a taxpayer-funded government institution, we feel it is very important to be transparent about how our parks are run.</p>
        <p class="m-1">We make our data and statistics as accessible as possible, for you to be able to understand how we try to give you the best parks we can.</p>
    </div>
    <div class="m-2">
        <h2>Check out the other report pages, to see graph and visual data representations!</h2>
        <div class="reports-section">
            <h4>Our Parks</h4>
            <div>
                <strong>Parks managed by Parks Authority</strong> @Model.ParkCount.
            </div>
            <div>
                <strong>The total area of these parks</strong> @Model.TotalParkArea m&sup2;.
            </div>
            <div>
                <strong>Average Clubs per park</strong> @Model.AverageClubsPerPark.
            </div>
            <div>
                <strong>Clubs per park ranges from </strong> @Model.MinClubsPerPark to @Model.MaxClubsPerPark.
            </div>
            <div>
                <strong>Average Events currently scheduled per park</strong> @Model.AverageEventsPerPark.
            </div>
            <div>
                <strong>Number of scheduled events per park ranges from </strong> @Model.MinEventsPerPark to @Model.MaxEventsPerPark.
            </div>
            <a class="btn btn-info"  asp-action="Parks" asp-controller="Reports">See Park Graphs</a>
        </div>
        <div class="reports-section">
            <h4>Sports Clubs</h4>
            <div>
                <strong>We have</strong> @Model.ClubCount <strong>Clubs in our parks.</strong>.
            </div>
            <div>
                <strong>On average, each of our clubs have</strong> @Model.AverageClubMembers <strong>members</strong>.
            </div>
            <div>
                <strong>Our largest club is</strong> @Model.LargestClub.Item2, <strong>with </strong> @Model.LargestClub.Item1.
            </div>
            <div>
                <strong>The average membership for each club is </strong> £@Model.AverageClubMembership.
            </div>
            <div>
                @Model.MostPopularSport <strong>is our most popular sport, amongst our clubs</strong>
            </div>
            <a class="btn btn-info"  asp-action="SportsClubs" asp-controller="Reports">See Club Graphs</a>
        </div>
        <div class="reports-section">
            <h4>Organised Upcoming Events</h4>
            <div>
                <strong>Right now,</strong> @Model.EventCount <strong>events are scheduled in our parks.</strong>
            </div>
            <div>
                <strong>In</strong> @Model.MostPopularMonth <strong>, we expect the most number of events to happen!</strong>
            </div>
            <div>
                <strong>With the least current booked in</strong> @Model.LeastPopularMonth
            </div>
            <div>
                <strong>The most popular day of the week for an event is</strong> @Model.MostPopularDayOfWeek.
                <strong>Whereas </strong> @Model.LeastPopularDayOfWeek<strong> is the least popular day for an event.</strong>
            </div>
            <a class="btn btn-info"  asp-action="ParkEvents" asp-controller="Reports">See Park Event Graphs</a>
        </div>
        <div class="reports-section">
            <h4>Supervisors and Staff</h4>
            <div>
                <strong>Currently, on average our supervisors have been protecting parks for</strong> @Model.AverageTenure years.
            </div>
            <div>
                <strong>On average a Supervisor earns</strong> £@Model.AverageSalary pa.
            </div>
            <div>
                <strong>The correlation between Salary and area of park that they are repsonsible for is:</strong> R = @Model.RValueSalaryParkArea.
            </div>
            <div>
                <strong>The correlation between Salary and their tenure  is:</strong> R = @Model.RValueSalaryTenure.
            </div>
            <div>
                <strong>The longest serving supervisor has been pretecting our parks for</strong> @Model.LongestTenure years!
            </div>
            <a class="btn btn-info"  asp-action="Supervisors" asp-controller="Reports">See Staff Graphs</a>
        </div>
        <div class="reports-section">
            <h4>Our Shop</h4>
            <div>
                <strong>Since opening, our shop has had</strong> @Model.TotalOrders <strong>orders.</strong>
            </div>
            <div>
                <strong>With</strong> @Model.TotalItemsOrdered <strong>items ordered in total.</strong>
            </div>
            <div>
                <strong>On average each order has </strong> @Model.AverageOrderItems <strong>items.</strong>
            </div>
            <div>
                <strong>Each order we have processed has an overall average value of</strong> £@Model.AverageOrderValue <strong>. Whic goes straight back into supporting our parks!</strong>
            </div>
            <a class="btn btn-info" asp-action="Shop" asp-controller="Reports">See Shop Graphs</a>
        </div>
        <div>
        </div>
    </div>
</div>

LocalParks/Views/Reports/ParkEvents.cshtml
@model ChartViewModel
@{
    ViewData["Title"] = "Reports";
}

<div class="reports-jumbotron-img">
    <div class="p-1 pr-3 pl-3 bg-light rounded w-auto d-inline-block">
        <h1>Statistics for events in our parks</h1>
    </div>
</div>

<div class="bg-white p-2 rounded">
    <div class="chart-vertical-message">
        Tip: Rotating your screen may help to see the charts.
    </div>
    @await Component.InvokeAsync("EventsPerMonthChart")
</div>

LocalParks/Views/Reports/Parks.cshtml
@model ChartViewModel
@{
    ViewData["Title"] = "Reports";
}

<div class="reports-jumbotron-img">
    <div class="p-1 pr-3 pl-3 bg-light rounded w-auto d-inline-block">
        <h1>Reports about our parks</h1>
    </div>
</div>
<div class="bg-white p-2 rounded">
    <div class="chart-vertical-message">
        Tip: Rotating your screen may help to see the charts.
    </div>
    <div>
        @await Component.InvokeAsync("ParksPerPostcodeChart")
    </div>

    <div>
        @await Component.InvokeAsync("TotalParkAreaPerPostcodeChart")
    </div>
</div>

LocalParks/Views/Reports/Shop.cshtml
@model ChartViewModel
@{
    ViewData["Title"] = "Reports";
}

<div class="reports-jumbotron-img">
    <div class="p-1 pr-3 pl-3 bg-light rounded w-auto d-inline-block">
        <h1>Shop Statistics and Data</h1>
    </div>
</div>
<div class="bg-white p-2 rounded">
    <div class="chart-vertical-message">
        Tip: Rotating your screen may help to see the charts.
    </div>
    @await Component.InvokeAsync("PopularShopProductsChart")
</div>

LocalParks/Views/Reports/SportsClubs.cshtml
@model ChartViewModel
@{
    ViewData["Title"] = "Reports";
}

<div class="reports-jumbotron-img">
    <div class="p-1 pr-3 pl-3 bg-light rounded w-auto d-inline-block">
        <h1>Information about our sports clubs</h1>
    </div>
</div>
<div class="bg-white p-2 rounded">
    <div class="chart-vertical-message">
        Tip: Rotating your screen may help to see the charts.
    </div>
    <div>
        @await Component.InvokeAsync("SportPercentageChart")
    </div>
    <div>
        @await Component.InvokeAsync("ClubMembersByParkAreaChart")
    </div>
</div>

LocalParks/Views/Reports/Supervisors.cshtml
@model ChartViewModel
@{
    ViewData["Title"] = "Reports";
}

<div class="reports-jumbotron-img">
    <div class="p-1 pr-3 pl-3 bg-light rounded w-auto d-inline-block">
        <h1>Staff statistics</h1>
    </div>
</div>
<div class="bg-white p-2 rounded">
    <div class="chart-vertical-message">
        Tip: Rotating your screen may help to see the charts.
    </div>
    @await Component.InvokeAsync("SalaryTenureChart")
</div>